"""Targets are generated by the game's own physics engine from a hidden
ground truth. That guarantees every target is exactly reproducible by the moves
the player has -- there is no unreachable "experimental" map to chase.
"""
from __future__ import annotations

import hashlib
import os
from dataclasses import dataclass

import numpy as np

from . import analysis as an
from .physics import A_TYPE, B_TYPE, Polymer, SimParams, simulate_ensemble

CACHE_DIR = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), ".cache")


@dataclass(frozen=True)
class Level:
    name: str
    blurb: str
    n: int
    n_loops: int
    block_min: int
    block_max: int
    burn_in: int = 8000
    n_samples: int = 1200
    sample_every: int = 25

LEVELS = [
    #                              n  loops  block_min  block_max
    Level("Couple of Loops",
          "A and B blocks phase-separate. Paint the ribbon to match the plaid.",
          20, 6, 3, 5),
    Level("The Story of a TAD",
          "Loops pin two beads together and create a bright dot off the diagonal.",
          35, 10, 5, 6),
    Level("TADs + compartments",
          "Loops carve TAD squares on top of the compartment checkerboard.",
          50, 25, 10, 8),
    Level("Full locus",
          "Multiple TADs, fine compartments, nested loops — a real Hi-C puzzle.",
          100, 40, 15, 12),
]

class Target:
    """Ground truth + the maps derived from it."""

    def __init__(self, level: Level, seed: int, types, loops, P, C, e1, oe):
        self.level = level
        self.seed = seed
        self.types = types
        self.loops = loops
        self.P = P
        self.C = C
        self.e1 = e1
        self.oe = oe
        self.n = level.n


def _ground_truth(level: Level, rng: np.random.Generator):
    n = level.n
    # --- compartments: alternating blocks of random length
    types = np.empty(n, dtype=np.int8)
    cur = int(rng.choice([A_TYPE, B_TYPE]))
    i = 0
    while i < n:
        L = int(rng.integers(level.block_min, level.block_max + 1))
        types[i:i + L] = cur
        cur = -cur
        i += L
    if len(np.unique(types)) == 1:          # degenerate guard
        types[n // 2:] = -types[0]

    # --- loops: CTCF-like anchors, preferentially at block boundaries
    bounds = [k for k in range(2, n - 2) if types[k] != types[k - 1]]
    loops: list[tuple[int, int]] = []
    tries = 0
    while len(loops) < level.n_loops and tries < 500:
        tries += 1
        if bounds and rng.random() < 0.65:
            i = int(rng.choice(bounds))
        else:
            i = int(rng.integers(0, n - 4))
        span = int(rng.integers(5, max(6, n // 2)))
        j = i + span
        if j >= n:
            continue
        if any(max(abs(i - a), abs(j - b)) < 3 for a, b in loops):
            continue
        if any(i in (a, b) or j in (a, b) for a, b in loops):
            continue
        loops.append((i, j))
    loops.sort()
    return types, loops


def _cache_key(level: Level, seed: int) -> str:
    par = SimParams()
    sig = f"{level.name}|{level.n}|{level.n_loops}|{level.block_min}|{level.block_max}|" \
          f"{seed}|{par.eps_AA}|{par.eps_BB}|{par.eps_AB}|{par.eps_domain}|{par.sigma}|" \
          f"{par.ev_eps}|{par.k_loop}|{par.contact_rc}|v3"
    return hashlib.md5(sig.encode()).hexdigest()[:16]


def build_target(level: Level, seed: int, progress=None) -> Target:
    """Load a cached target or run the hidden ground-truth simulation."""
    os.makedirs(CACHE_DIR, exist_ok=True)
    path = os.path.join(CACHE_DIR, f"target_{_cache_key(level, seed)}.npz")
    if os.path.exists(path):
        try:
            z = np.load(path, allow_pickle=False)
            types, loops_arr, P = z["types"], z["loops"], z["P"]
            loops = [tuple(int(v) for v in row) for row in loops_arr.reshape(-1, 2)]
            oe, C, e1 = an.pipeline(P, types.astype(float))
            if progress:
                progress(1.0)
            return Target(level, seed, types, loops, P, C, e1, oe)
        except Exception:
            pass  # corrupt cache -> just rebuild

    rng = np.random.default_rng(seed)
    types, loops = _ground_truth(level, rng)
    poly = Polymer(level.n, SimParams(), seed=seed + 1000)
    poly.load_config(types, loops)
    P = simulate_ensemble(poly, level.burn_in, level.n_samples, level.sample_every, progress)
    oe, C, e1 = an.pipeline(P, types.astype(float))
    try:
        np.savez_compressed(path, types=types,
                            loops=np.array(loops, dtype=np.int32).reshape(-1, 2), P=P)
    except Exception:
        pass
    return Target(level, seed, types, loops, P, C, e1, oe)
